### PR TITLE
Backend business logic

### PR DESCRIPTION
**Pull request by Daves2126**

### CODE REVIEW

**Comment by dfgarciac1** [comment]
I see a good MR, add good practices **Very good mondongo**

**Comment by dfgarciac1** [comment]
Review of MR Backend business logic #35:

Overall, the MR (Merge Request) appears to be a substantial one with 9 commits and changes to 41 files. Here is a breakdown of the review:

Description: The MR lacks a description. It is important to provide a clear and concise description of the changes made in the MR to help reviewers understand the purpose and scope of the changes.

Commits: The MR consists of 9 commits made by egonzalezt and others over the last week. It is advisable to ensure that each commit has a meaningful and descriptive commit message, summarizing the changes made in that commit. This helps in understanding the changes at a glance and facilitates easier code review.

Changes: The MR includes changes related to websockets, sockets, upload mods view, upload mods status component, upload files fix, update mods improvement, server.properties editor, and elastic. It would be helpful to have more context regarding these changes, their purpose, and their impact on the overall project. This can be provided in the description or through inline comments.

File changes: The MR affects 41 files. It is essential to review each file thoroughly to ensure that the changes made align with the intended goals of the MR and do not introduce any unintended issues or conflicts.

Lack of checks: The MR does not mention any checks that have been performed. It is important to conduct necessary tests, such as unit tests, integration tests, or any other relevant checks, to ensure the changes do not introduce regressions or break existing functionality.

To provide a more detailed review, it would be helpful to have access to the actual code changes, diff, and any additional information regarding the purpose and impact of the MR. This would enable a more comprehensive assessment of the changes made.

Remember, it is essential to communicate and collaborate with the MR author to address any concerns or questions that arise during the review process.

**Review by dfgarciac1 — APPROVED** [review]
Si

**Review by ccanasj — APPROVED** [review]
Hola!
Me has atrapado
En medio-suavemente
Te traigo mi suave
Regresé de entre los muertos
con música de You Tube
que cumple con los derechos de autor
disfruta de la gloriosa suavidad
conmigo bajo mi gobierno
viviremos a mil
suavemente
mi corazón
Es tiempo de suavemente
te darás cuenta de que suavemente
es para siempre
la luna y el sol morirán
pero la suavidad es suave
las estrellas brillarán intensamente
todos sabrán suavemente lo que suave es
suavemente de nuevo
un millon de veces suavemente
multiplicado por otro millón
disfruta de la gloriosa suavidad
conmigo bajo mi gobierno
viviremos a mil
suavemente

**Pull request merged**
